FROM ubuntu:20.04

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y update    

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install   \
               apt-utils \
               man       \
               manpages  \
               make      \
               ssh       \
               tcsh      \
               emacs     \
               sudo      

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install   \
               cmake     \
               git       

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install   \
               gcc-10    \
               g++-10    

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install             \
               libtbb2             \
               libtbb-dev           

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install             \
               locate              \
               &&                  \
               updatedb         


RUN apt-get -y clean
RUN apt-get -y update

USER root
RUN \
       update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90 --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
    && update-alternatives --install /usr/bin/cc  cc /usr/bin/gcc 30						  \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30						  


RUN useradd -m ubuntu

USER ubuntu
RUN mkdir /home/ubuntu/NWmath
WORKDIR /home/ubuntu/


ENV SHELL       /bin/bash
